name: upstream_home_assignment
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - pandas
  - pytest
  - black
  - flake8
  - docker-py
  - pip:
      - pyspark==3.5.0
      - dagster